### PR TITLE
Bootstrapped Code into Python Module

### PR DESCRIPTION
**Pull request by jjangsangy**
Hooked up into `setuptools` machinery for better maintainability of the module codebase.

# Revision Change
* Separation of concern. Moved relevant functionality into separate files.
* Running `python -m alchemyapi` now direct replacement for running `python alchemyapi.py`
* Run `python setup.py tests` runs unit tests
* Run `python setup.py install` installs module into codebase

# Note
* Relevant `setup.py` boilerplate has been set to be filled in by library maintainer.

### CODE REVIEW

**Comment by jjangsangy** [comment]
Was wondering if anyone could take a look at this?

**Comment by AlchemyAPI** [comment]
Hi Sang,

We have some SDK discussions going on internally that we'll need to
conclude before we can incorporate your work.

We appreciate your contribution, but unfortunately our process is not as
fast as we might like.

Regards,

Stuart Horner
AlchemyAPI

**Comment by jjangsangy** [comment]
Hi Thanks you for your response.

If there are any ways, that I can help implement anything that would help speed up the process please let me know.

I have also re-implemented this entire API in a way that is more conforming to current day standards. As well as following pretty strict PEP8 and standards laid out by the [Python Packaging Authority](https://packaging.python.org/en/latest/)

https://github.com/jjangsangy/AlchemyAPI

Also, this version of the API passes all the unit tests that were created from this original SDK but retrofitted to the newer API that I am proposing.

I've also integrated the entire package into Continuous Integration using TravisCI showing how all the tests pass.

https://travis-ci.org/jjangsangy/AlchemyAP

I hope that providing these services, can provide some security into making this transition more agile. 

Thank you guys also for building this service. The reason for building these is because I personally enjoyed using your API's and just wanted to help contributing back through the open source community. If there are any questions, please let me know of how I can be of any assistance!

Thanks

- Sang Han

**Comment by jjangsangy** [comment]
Closed this PR due to lack of code review and inactivity.

**Pull request closed without merging**
